<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ejercicio1.aspx.cs" Inherits="TP6_Grupo19_2_.Ejercicio1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Productos</title>
</head>

<body>
    <form id="form1" runat="server">

        <div style="font-size:40px; font-weight:bold;">
            Productos
            <br />
            <br />
        </div>

        <asp:GridView ID="gvProductos" runat="server"
            AutoGenerateColumns="False"
            AutoGenerateEditButton="True"
            AutoGenerateDeleteButton="True"
            AllowPaging="True"
            PageSize="10"
            DataKeyNames="IdProducto"
            OnPageIndexChanging="gvProductos_PageIndexChanging"
            OnRowDeleting="gvProductos_RowDeleting"
            OnRowEditing="gvProductos_RowEditing"
            OnRowCancelingEdit="gvProductos_RowCancelingEdit"
            OnRowUpdating="gvProductos_RowUpdating">

            <Columns>

                <asp:TemplateField HeaderText="Id Producto">
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_idProducto"
                            runat="server"
                            Text='<%# Bind("IdProducto") %>'>
                        </asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Nombre Producto">
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_NombreProducto"
                            runat="server"
                            Text='<%# Bind("NombreProducto") %>'>
                        </asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txt_eit_NombreProducto"
                            runat="server"
                            Text='<%# Bind("NombreProducto") %>'>
                        </asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Cantidad Por Unidad">
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_CantidadPorUnidad"
                            runat="server"
                            Text='<%# Bind("CantidadPorUnidad") %>'>
                        </asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txt_eit_CantidadPorUnidad"
                            runat="server"
                            Text='<%# Bind("CantidadPorUnidad") %>'>
                        </asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Precio Unidad">

                    <ItemTemplate>
                        <asp:Label ID="lbl_it_PrecioUnidad"
                            runat="server"
                            Text='<%# Bind("PrecioUnidad") %>'>
                        </asp:Label>
                    </ItemTemplate>

                    <EditItemTemplate>

                        <asp:TextBox ID="txt_eit_PrecioUnidad"
                            runat="server"
                            Text='<%# Bind("PrecioUnidad") %>'>
                        </asp:TextBox>

                        <asp:RequiredFieldValidator
                            ID="rfvPrecioUnidad"
                            runat="server"
                            ControlToValidate="txt_eit_PrecioUnidad"
                            ErrorMessage="*"
                            ForeColor="Red">
                        </asp:RequiredFieldValidator>

                        <asp:RegularExpressionValidator
                            ID="revPrecioUnidad"
                            runat="server"
                            ControlToValidate="txt_eit_PrecioUnidad"
                            ValidationExpression="^\d+([\,\.]\d+)?$"
                            ErrorMessage="Ingrese solo números"
                            ForeColor="Red">
                        </asp:RegularExpressionValidator>

                    </EditItemTemplate>

                </asp:TemplateField>

            </Columns>

            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />

        </asp:GridView>

        <br />

    </form>
</body>
</html>